### ISSUE TITLE
Internal representation of all variables (curr_var_tab)

### ISSUE THREAD

**Issue by reinholdsson** [SwedishPensionsAgency/Coldbir#76]
As we need to simplify some of the code, it would be nice to have better representation of the all variables in `curr_var_tab` - this would also remove some of the issues related to `data.table`. A suggestion after discussion with @mikula is that we will keep an internal representation of the variables in a hierarchical list:

```
$Age
  - 2012
     - 11
       - list()
     - 12
       - list()  # a["Age", c(2012, 12)]
     - list()  # a["Age", 2012]
  - 2013
     - 1
       - list()
     - 2
       - list()
  - list()  # a["Age", NULL]
```

And then use recursive functions when subsetting/matching. Similar to the package `Hierarchy`.

**Comment by mikula** [comment]
# there are several available options
  # for example
ENDNODE <- list()
zzz <- list(
            "var1"=list(
                    "." = ENDNODE,
                    "2001"=list(
                              "." = ENDNODE,
                              "1"= list("."=ENDNODE),
                              "2"= list("."=ENDNODE)
                              ),
                    "2002"=list(
                              "." = ENDNODE,
                              "1"= list("."=ENDNODE),
                              "2"= list("."=ENDNODE)
                              )
                    ),
            "var2"=list(
              "." = ENDNODE,
              "2001"=list(
                "." = ENDNODE,
                "1"= list("."=ENDNODE),
                "2"= list("."=ENDNODE)
              ),
              "2002"=list(
                "." = ENDNODE,
                "1"= list("."=ENDNODE),
                "2"= list("."=ENDNODE)
              )
            )
          )

str(zzz)
  # List of 2
  # $ var1:List of 3
  # ..$ .   : list()
  # ..$ 2001:List of 3
  # .. ..$ .: list()
  # .. ..$ 1:List of 1
  # .. .. ..$ .: list()
  # .. ..$ 2:List of 1
  # .. .. ..$ .: list()
  # ..$ 2002:List of 3
  # .. ..$ .: list()
  # .. ..$ 1:List of 1
  # .. .. ..$ .: list()
  # .. ..$ 2:List of 1
  # .. .. ..$ .: list()
  # $ var2:List of 3
  # ..$ .   : list()
  # ..$ 2001:List of 3
  # .. ..$ .: list()
  # .. ..$ 1:List of 1
  # .. .. ..$ .: list()
  # .. ..$ 2:List of 1
  # .. .. ..$ .: list()
  # ..$ 2002:List of 3
  # .. ..$ .: list()
  # .. ..$ 1:List of 1
  # .. .. ..$ .: list()
  # .. ..$ 2:List of 1
  # .. .. ..$ .: list()

str(zzz[["var1"]][["2001"]])
  # List of 3
  # $ .: list()
  # $ 1:List of 1
  # ..$ .: list()
  # $ 2:List of 1
  # ..$ .: list()

str(zzz[["var1"]][["."]])
  #  list()

zzz[["var1"]][["2001"]][["1"]] 
  #  list()

str(zzz[["var1"]][["2001"]][["5"]])
  #  NULL

**Comment by mikula** [comment]
# even better. ENDNODE <- 1 implies extra functionality

ENDNODE <- 1
zzz <- list(
            "var1"=list(
                    "." = ENDNODE,
                    "2001"=list(
                              "." = ENDNODE,
                              "1"= list("."=ENDNODE),
                              "2"= list("."=ENDNODE)
                              ),
                    "2002"=list(
                              "." = ENDNODE,
                              "1"= list("."=ENDNODE),
                              "2"= list("."=ENDNODE)
                              )
                    ),
            "var2"=list(
              "." = ENDNODE,
              "2001"=list(
                "." = ENDNODE,
                "1"= list("."=ENDNODE),
                "2"= list("."=ENDNODE)
              ),
              "2002"=list(
                "." = ENDNODE,
                "1"= list("."=ENDNODE),
                "2"= list("."=ENDNODE)
              )
            )
          )

str(zzz)
  #   $ var1:List of 3
  #   ..$ .   : num 1
  #   ..$ 2001:List of 3
  #   .. ..$ .: num 1
  #   .. ..$ 1:List of 1
  #   .. .. ..$ .: num 1
  #   .. ..$ 2:List of 1
  #   .. .. ..$ .: num 1
  #   ..$ 2002:List of 3
  #   .. ..$ .: num 1
  #   .. ..$ 1:List of 1
  #   .. .. ..$ .: num 1
  #   .. ..$ 2:List of 1
  #   .. .. ..$ .: num 1
  #   $ var2:List of 3
  #   ..$ .   : num 1
  #   ..$ 2001:List of 3
  #   .. ..$ .: num 1
  #   .. ..$ 1:List of 1
  #   .. .. ..$ .: num 1
  #   .. ..$ 2:List of 1
  #   .. .. ..$ .: num 1
  #   ..$ 2002:List of 3
  #   .. ..$ .: num 1
  #   .. ..$ 1:List of 1
  #   .. .. ..$ .: num 1
  #   .. ..$ 2:List of 1
  #   .. .. ..$ .: num 1

> unlist(zzz)
>   #   var1..   var1.2001.. var1.2001.1.. var1.2001.2..   var1.2002.. var1.2002.1.. var1.2002.2..        var2.. 
>   #   1             1             1             1             1             1             1             1 
>   #   var2.2001.. var2.2001.1.. var2.2001.2..   var2.2002.. var2.2002.1.. var2.2002.2.. 
>   #   1             1             1             1             1             1 

sum(unlist(zzz))
   # [1] 14

sum(unlist(zzz[["var1"]]))
   # [1] 7

**Comment by mikula** [comment]
An additional sugestion.

The tree should always be sorted. 

We need 
compare <- function(nod1,nod2) {

```
... return(1L)   #   if name(node1) > name(node2) , if both are  proper numbers handle as numbers

... return(0L)  #   if name(node1) == name(node2), if both are  proper numbers handle as numbers

... return(-1L)#   if name(node1) < name(node2), if both are  proper numbers handle as numbers
```

}

then the insert- and delete- operations are easy to implement

This will assert that all results will be sorted as default

**Comment by reinholdsson** [comment]
Wrapping the return value in `utils::modifyList` with an `order` function makes the returned list sorted.

```
insert <- function (x, val) {
  stopifnot(is.list(x), is.list(val))
  for (v in names(val)) {
    x[[v]] <- if (v %in% names(x) && is.list(x[[v]]) && is.list(val[[v]])) {
      insert(x[[v]], val[[v]])
    } else val[[v]]
  }
  return(x[gtools::mixedorder(names(x))])
}

```

where gtools::mixedorder` is used in order to also sort the numerical names correctly.

```

x <- list(a = list(b = list(c = 1, e = 1), g = 1, h = 1))
y <- list(a = list(b = list(c = NULL, d = 1), f = 1, g = NULL))
insert(x, y)

# $a
# $a$b
# $a$b$d
# [1] 1
# 
# $a$b$e
# [1] 1
# 
# 
# $a$f
# [1] 1
# 
# $a$h
# [1] 1
```

Another solution - with improved performance - would be to split the existing list within the `for`-loop and then put together the list again - I guess, something like:

```
y <- list()
y[1:(i-1)] <- x[1:(i-1)]  # keep this part
y[i] <- val  # add new value
y[(i+1):(length(x)+1)] <- x[i:length(x)]  # move 2:nd previous part one step upwards
return(y)
```

**Comment by reinholdsson** [comment]
Function to create a recursive list from a vector:

```
rec_lst <- function(x) {
  r <- list()
  r[[x[1]]] <- if (length(x[-1]) != 0) rec_lst(x[-1]) else 1
  return(r)
}

rec_lst(c("a", "b", "c"))

# $a
# $a$b
# $a$b$c
# [1] 1
```

This might come to use when converting a variable path including dimensions to a nested list representation.

**Comment by reinholdsson** [comment]
I don't remember the conclusion of our discussion, should we store the list representation on file - instead of reading the whole database file structure each time `cdb(...)` is called?

**Comment by mikula** [comment]
In my humble opinion:
I would prefer to keep it memory based. Otherwise it could be costly each time we write new data to the database. It is already resource-demanding to updating of the config-file. Coldbir will never be a general-purpose database. Speed and easy handling must be the priority. The most common use will be bulk-loading and distributtion of  read-only huge data sets  and as a vehicle for temporary storage for a single user. Multiuser with simultaneous updating demands lot more complexity, far beyond scoop of this project, I suppose.

**Comment by reinholdsson** [comment]
Odd behaviour of `mixedorder`?

```
gtools::mixedorder(c("var2", "var1"))
[1] 2 1
gtools::mixedorder(c("var2"))
[1] 2 1
```

**Comment by elenius** [comment]
In case the vector has length 1 it seems to split up the character part and the numerical part. But only sorts characters and numbers between and not within type. It seems to be a bug.

```
x <- c("b", "2", "a", "1")
mixedorder(x)
[1] 4 2 3 1
mixedorder(paste(x, collapse=""))
[1] 2 4 1 3
```

**Comment by reinholdsson** [comment]
@elenius thanks, you're right! As a temporary solution I added `if (length(x) > 1)`. Later we might do our own order function instead.

Still some things to complete with methods `add_repr`/`del_repr`, e.g.

```
a$variables <- list()
a$add_repr("var1", 2012)
a$add_repr("var1", c(2012, 12))
a$variables
# $var1
# $var1$`2012`
# $var1$`2012`$`12`
# [1] 1
```

should rather be something like as @mikula described above:

```
# a$variables$var1$`2012` <- list(. = 1, `12` = 1)

# $var1
# $var1$`2012`
# $var1$`2012`$.
# [1] 1
# 
# $var1$`2012`$`12`
# [1] 1
```
- [x] add `.` to list in `sorted_modify_list`.

**Comment by reinholdsson** [comment]
@mikula sounds like a good idea, I agree.

```
a <- cdb(tempfile())
a$add_repr("var1", 2012)
a$add_repr("var1", c(2012,12))
a$add_repr("var1", c(2013,12))
a$variables
a$del_repr("var1", c(2013,12))
a$variables
```

I need to find a way to delete a branch from the tree, if all its end nodes are empty, @mikula do you have any suggestions?

```
rapply(a$variables, function(x) if(sum(unlist(x)) > 0) x else NULL, how = "replace")
# => possible solution?
```
- [ ] find solution to delete branch from tree

**Comment by reinholdsson** [comment]
One solution on how to delete all branches with recursive sum == 0:

```
clear_branch <- function (x) {
  for (i in names(x)) {
    if (sum(unlist(x[[i]])) == 0) {
      x[[i]] <- NULL
    } else x[[i]] <- clear_branch(x[[i]])
  }
  return(x)
}
```

**Comment by reinholdsson** [comment]
Work in progress ...

```
library(Coldbir)
a <- cdb(tempfile())

a[] <- MASS::survey
sum(unlist(a$variables))
# [1] 12

a[, c(2012)] <- MASS::survey
sum(unlist(a$variables))
# [1] 24

a[, c(2012, 12)] <- MASS::survey
sum(unlist(a$variables))
# [1] 36

a["Exer", c(2012)] <- NULL
sum(unlist(a$variables))
# [1] 35
```

### Todo
- [ ] Replace `a$curr_var_tab` with `a$variables` (also includes code refactoring as we are using `list` instead of `data.table`).

**Comment by reinholdsson** [comment]
Perhaps for later, but we could use `singleton(...)` whenever requesting the `variables` list, instead of running `update_repr_from_file` when `cdb(...)` is initialized.

**Comment by reinholdsson** [comment]
- [x] Find a better way (than using `eval`) to get a value from the list representation.

```
name <- "Exer"
dims <- c(2012, 12)
eval(parse(text = paste("a$variables[['", paste(c(name, dims), collapse = "']][['"), "']]", sep = "")))
# $.
# [1] 1
```

**Comment by reinholdsson** [comment]
```
list_match <- function (x, val) {
  for (v in names(val)) {

    # If the name doesn't exist in the other list => 0
    if (v %in% names(x)) {

      # If any of the recursive sums are 0 => 0
      if (sum(unlist(x[[v]])) == 0 || sum(unlist(val[[v]])) == 0) {
        val[[v]] <- list(. = 0)

      # If both are lists run function recursevily
      } else if (is.list(x[[v]]) && is.list(val[[v]])) {
        val[[v]] <- list_match(x[[v]], val[[v]])
      } else if (x[[v]] != 1 && val[[v]] != 1) {
        val[[v]] <- list(. = 0)
      }
    } else val[[v]] <- list(. = 0)
  }

  if (length(names(val)) > 1) {
    val <- val[gtools::mixedorder(names(val))]
  }

  val <- clear_branch(val)
  if (length(val) == 0) val <- NULL

  return(val)
}

lst <- recursive_list(c("W.Hnd", 2012), list(. = 1))
list_match(a$variables, lst)
list_match(lst, a$variables)

lst <- recursive_list(c("W.Hnd", 2013), list(. = 1))
list_match(a$variables, lst)
list_match(lst, a$variables)
```

**Comment by reinholdsson** [comment]
I have added support for `.all` and `._` in `list_match()`. The first argument is the data list, and the second the matching list (that may also contain wild cards). E.g.

```
library(Coldbir)
a <- cdb(tempfile())
a[] <- MASS::survey
a[, c(2012)] <- MASS::survey
a[, c(2012, 12)] <- MASS::survey
a[, c(2013, 11)] <- MASS::survey
a[, c(2013, 12)] <- MASS::survey
a["Exer", c(2012)] <- NULL

lst <- Coldbir:::recursive_list(c("W.Hnd", ._, ._), list(. = 1))
Coldbir:::list_match(a$variables, lst)

lst <- Coldbir:::recursive_list(c("W.Hnd", ._), list(. = 1))
Coldbir:::list_match(a$variables, lst)

lst <- Coldbir:::recursive_list(c("W.Hnd", .all), list(. = 1))
Coldbir:::list_match(a$variables, lst)
```

Currently it doesn't allow for wild cards in the first argument. This is not necessary as we are only using this function internally within the package - but, it might be a nice feature.

**Comment by reinholdsson** [comment]
Solution to `eval` problem above.

```
x <- list(a = list(b = list(c = 1), d = 1))
sel <- c("a", "b", "c")

# Eval solution
fun1 <- function(x, sel) {
  eval(parse(text = paste("x[['", paste(sel, collapse = "']][['"), "']]", sep = "")))
}

# Recursive solution
fun2 <- function(x, sel) {
  if (length(sel) > 1) fun2(x[[sel[1]]], sel[-1]) else x[[sel]]
}

fun1(x, sel)
fun2(x, sel)
```

**Comment by reinholdsson** [comment]
This means that we now have helper functions for:
- **Matching query** (even when using wild cards)

```
lst <- Coldbir:::recursive_list(c(name, dims), list(. = 1))
Coldbir:::list_match(a$variables, lst)
```
- **Check if variable exists**

```
!is.null(Coldbir:::subset_list(a$variables, c(name, dims)))
```

alternatively

```
lst <- Coldbir:::recursive_list(c(name, dims), list(. = 1))
sum(unlist(Coldbir:::list_match(a$variables, lst))) == 1
```
- **Query data** (`[`)
- [x] Convert each node of a list to character vectors

E.g.

```
lst <- Coldbir:::recursive_list(c("Exer", ._, ._), list(. = 1))
x <- names(unlist(Coldbir:::list_match(a$variables, lst)))
x <- lapply(x, function(x) {
  x <- strsplit(x, "\\.")[[1]]
  x <- x[nchar(x) > 0]
  list(name = x[1], dims = x[2:length(x)])
})

gen_name <- function(name, dims) paste(name, paste(dims, collapse="."),sep="_")
read_var <- function(...) a$get_variable(...)

# Create data.table with first variable
v <- data.table(V1 = a$get_variable(name = x[[1]]$name, dims = x[[1]]$dims))
setnames(v, gen_name(x[[1]]$name, x[[1]]$dims))

# Add all other variables
for(i in 2:length(x)){
  v[ , gen_name(x[[i]]$name, x[[i]]$dims) := read_var(x[[i]]$name, x[[i]]$dims), with = F]
}
```

**Comment by reinholdsson** [comment]
Possible performance improvements :)
- New: `get_v`
- Old: `[`

```
a <- cdb(tempfile())
a["Exer", 2012] <- sample(1:10, 10000000, replace = T)
a["Clap", 2013] <- sample(1:10, 10000000, replace = T)
a["Exer", c(2012, 1)] <- sample(1:10, 10000000, replace = T)
a["Exer", c(2012, 2)] <- sample(1:10, 10000000, replace = T)
a["Exer", c(2012, 12)] <- sample(1:10, 10000000, replace = T)

system.time(a$get_v("Exer", c(._,._)))
# user  system elapsed 
# 0.33    0.04    0.38 
system.time(a["Exer", c(._,._)])
# user  system elapsed 
# 0.65    0.08    0.73 
```

**Comment by reinholdsson** [comment]
Still need to figure out how to deal with `.` in names in `list_to_query_repr()`. Either disallow `.`, or find another solution (not using `names(unlist(x))`).

**UPDATE**: We solved it by disallowing "." :)

**Comment by reinholdsson** [comment]
Merged into `dev`.

**Comment by reinholdsson** [comment]
Further changes will have their own issues.
